export const DEFAULT_INTEREST_TAGS = [
  "AI & Machine Learning",
  "Web Development",
  "Mobile Apps",
  "Cloud Computing",
  "Cybersecurity",
  "Data Science",
  "Product Management",
  "UI/UX Design",
  "Graphic Design",
  "Entrepreneurship",
  "Startups",
  "Investing",
  "Personal Finance",
  "Marketing",
  "Content Creation",
  "Photography",
  "Video Production",
  "Writing",
  "Books & Literature",
  "Gaming",
  "Esports",
  "Board Games",
  "Tabletop RPGs",
  "Cooking",
  "Baking",
  "Coffee Culture",
  "Wine & Spirits",
  "Fitness",
  "Running",
  "Cycling",
  "Climbing",
  "Hiking",
  "Travel",
  "Sustainability",
  "Climate Action",
  "Volunteering",
  "Mental Health",
  "Mindfulness",
  "Yoga",
  "Parenting",
  "Pets & Animals",
  "Gardening",
  "DIY & Crafts",
  "Fashion",
  "Beauty & Skincare",
  "Live Music",
  "Music Production",
  "Languages",
  "Science & Space",
  "Philosophy",
  "Reading",
  "Crystals",
  "Astrology",
  "Sports Fan",
  "Football",
  "Basketball",
  "Soccer",
  "Tennis",
  "Golf",
  "Swimming",
  "Volleyball",
  "Fishing",
  "Hunting",
  "Martial Arts",
  "Yoga",
  "Dance",
  "Theater & Drama",
  "Surfing",
  "Skiing & Snowboarding",
  "Calisthenics",
  "Weightlifting",
  "CrossFit",
  "Pickleball",
  "Boxing",
  "Jiu-Jitsu",
  "K-Pop",
  "Manga",
  "Art",
  "Coaching",
] as const;

export type DefaultInterestTag = typeof DEFAULT_INTEREST_TAGS[number];
